### ISSUE TITLE
Help/Docs for template option in the capture menu

### ISSUE THREAD

**Issue by pjdurai** [Trevoke/org-gtd.el#100]
Greetings
Thanks for creating such an useful package!

In the capture menu, I see options like "Templates for projects" and "Centralized templates for projects...". I don't see these explained anywhere. I this some kind of mechanism to create projects (in gtd sense) with subtasks already filled in?

Could you please add some explanation about this somewhere?

Thanks a lot!

**Comment by Trevoke** [comment]
Hello,

I'm sorry to say but I'm not sure I know what you mean, could you share a
screenshot?

**Comment by pjdurai** [comment]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/207662/197087666-703279d3-f7cb-4ed4-abee-f28b0849d6a8.png">

**Comment by pjdurai** [comment]
I  use latest Doom emacs on  a Mac. I _was_ trying out various GTD related packages before I settled on org-gtd. May be this is caused by some residual config left by some other package?

**Comment by Trevoke** [comment]
Oh boy I'm sorry that I left this unanswered for so long.
Yes, most of this is likely to be a residue of some other package.

These capture templates are regimented by the variable `org-capture-templates`. Org-gtd actually takes some pains to ensure that whatever your current setup is, it does not override it. I'm afraid I'm not quite sure how to help you troubleshoot this other than look for places where that variable might be set in your configuration / customization files, sorry.

**Comment by Trevoke** [comment]
I am closing this issue because these are capture templates that were carried over from some other configuration; only the first two in that screenshot are from this package.

Please comment again if you have an issue with this, and open another issue if you have another problem!
