### ISSUE TITLE
Config mentions branch 2.0.0 which is not available

### ISSUE THREAD

**Issue by DouwMarx** [Trevoke/org-gtd.el#101]
Config mentions branch 2.0.0 which is not available

https://github.com/Trevoke/org-gtd.el/blame/master/doc/org-gtd.org#L163

I changed the config branch to "master". Is this the correct branch to use?

**Comment by Trevoke** [comment]
Ah! Thank you for the catch. Yes, master is fine, there is also a 2.0.0 tag if you want something that is guaranteed to be stable.

I will have to update that section of the documentation.
