### ISSUE TITLE
Internal functions declared as interactive commands

### ISSUE THREAD

**Issue by cdlm** [Trevoke/org-gtd.el#106]
One example is `org-gtd-projects-fix-todo-keywords` which expects a `marker` argument but has a bare `(interactive)` declaration and fails with `wrong number of argments` when called interactively. Disclaimer: I don't know markers in Emacs so I might just be wrong.

The intended command seems to be `org-gtd-projects-fix-todo-keywords-for-project-at-point` (confusingly, it also has the longest and most specific name of the two…)

**Comment by Trevoke** [comment]
Good point, that is something I forgot to clean up. Only the more specific name should be interactive, the other one is for programmatic use. This will be fixed in the next release, sometime today.

**Comment by Trevoke** [comment]
Fixed by 5f8a5ff121a498d21b659d029099bb35de8e22ab
