### ISSUE TITLE
org-gtd--refile-targets - function or variable?

### ISSUE THREAD

**Issue by doolio** [Trevoke/org-gtd.el#11]
Should `org-gtd--refile-targets` be a variable rather than a function?

**Comment by Trevoke** [comment]
It would be nicer if it were a variable, but it's a macro evaluation and ... If it's a variable, then we have to be careful to set up the variables before we load the package.

I'm making it a function to be a little nicer to the users, but there's definitely an argument to be made for simpler code -- and, of course, `use-package` has the `:init` keyword that probably exist for precisely this reason.

**Comment by doolio** [comment]
> If it's a variable, then we have to be careful to set up the variables before we load the package.

I see, I did not appreciate that point.
