### ISSUE TITLE
Make hooks dependent on action type (projectify, single-task, trash, archive) e.g. by passing action

### ISSUE THREAD

**Issue by DerBeutlin** [Trevoke/org-gtd.el#114]
Hi, 

I added a bunch of hooks to ``org-gtd-process-item-hooks`` to prompt me for more metadate on the tasks. I would like to prevent them from running for certain actions though. E.g. I don't want to add tags to Items that I am trashing.
One could implement this by passing the action type to the hook, then the hook could decide whether or not to run. This however would probably break existing configuration with hooks not accepting any arguments. Still that would be nicer than having ``org-gtd-trash-item-hooks`` and ``org-gtd-archive-item-hooks`` etc etc

**Comment by Trevoke** [comment]
I've thought about this before. The main reason I haven't done it was because I couldn't figure out the proper balance of usability to customization.
Like you I agree it's silly to add tags to trashed items.

For instance, does it make sense to just suggest that "actionable" and "non-actionable" might benefit from different hooks?
Should we really just accept that whatever you trash doesn't really need hooks?

I suppose after all, in the words of [Steve Yegge](https://steve-yegge.blogspot.com/2008/03/js2-mode-new-javascript-mode-for-emacs.html), "Let's face it: you could be a total lunatic, and Emacs has to make you happy. " so maybe the answer is to just provide _all the options_.

**Comment by DerBeutlin** [comment]
Yeah for me definitely the distinction between actionable and non-actionable is the important one (although delegate may or may not be the odd one out).  
I would be also happy with two separate hook-lists for that, although I think passing the action type to the hooks might be a bit more versatile and you can always choose to ignore that argument. The downside would be you would need to create lambda's for function like org-set-tags-function just to ignore the passed argument.

By the way I temporarily "fixed" this issue for me by advicing around ``org-gtd--decorate-item`` with the following
```
  (defun max/org-gtd-filter-non-actionable (orig-func &rest args)
  (let ((action (subr-name (car (cdr (backtrace-frame 8))))))
    (unless (member action '( "org-gtd--incubate" "org-gtd--calendar" "org-gtd--delegate" "org-gtd--quick-action" "org-gtd--trash"))
      (apply orig-func args))))
  (advice-add 'org-gtd--decorate-item :around #'max/org-gtd-filter-non-actionable)
  )
```
It's nice that this work however this will probably fail to work if we call org-gtd--decorate-item in different scopes.


On a similar note, is it on purpose that you don't run ``org-gtd--decorate-item`` in ``org-gtd--modify-project``. So if I want to add a task to a project I'm not asked for tags (and my other hooks also do not run)

**Comment by Trevoke** [comment]
It was on purpose that it didn't run, yes, but now I think that was a mistake. The reasoning was that we would just inherit the tags from the project headline, but now I think that's ... Not good enough, and we should run those hooks for every project action too (pull request and test welcome, if you have the time!)

Let me noodle a bit on the other one, I've been considering a large redesign of the codebase to make it more extensible and I think this fits right in.

**Comment by Trevoke** [comment]
With 3.0, this can now be customized with the function `org-gtd-organize-type-member-p`

https://github.com/Trevoke/org-gtd.el/blob/master/org-gtd-organize.el#L124

Let me know if you run into any trouble with it!
