### ISSUE TITLE
Use org-mode better with calendar items

### ISSUE THREAD

**Issue by Trevoke** [Trevoke/org-gtd.el#118]
We are using `SCHEDULED` for appointments, which is incorrect. Org-mode ( https://orgmode.org/manual/Deadlines-and-Scheduling.html ) says: 

> Deadline: Meaning: the task—most likely a TODO item, though not necessarily—is supposed to be finished on that date.
> Scheduled: Meaning: you are planning to start working on that task on the given date.

> Scheduling an item in Org mode should _not_ be understood in the same way that we understand _scheduling a meeting_. Setting a date for a meeting is just a simple appointment, you should mark this entry with a simple plain timestamp, to get this item shown on the date where it applies. This is a frequent misunderstanding by Org users. In Org mode, _scheduling_ means setting a date when you want to start working on an action item.

So we should:

- [x] change the "calendar" items to use a timestamp (maybe an APPOINTMENT property of sorts, for easier filtering in the agenda) and stop using SCHEDULED... 
- [x] create a function to help folks move from the "old" calendar items to the "new" calendar items as well.
- [x] And update the documentation.
- [x] make sure there's an agenda view for "whoopses" (things you were supposed to do on a given day that you didn't)

**Comment by Sinthoras7** [comment]
Hm, to be honest, I am not sure about this one. 
Yes this is what the documentation says and technically correct, but I don't really see the advantage for the user in not using SCHEDULED, but instead a custom property. 
If anything I see disadvantages for the user, because other applications reading the files (for example a mobile app, in my case orgzly) understand scheduled tasks correctly and display them on the agenda, while they would not with the appointment.

**Comment by Trevoke** [comment]
You bring up a good point re: tools like orgzly. I'll have to run a test. 

I *think* that, because the property would have an active timestamp, it would behave completely normally as far as anything org-mode-related is concerned when it comes to timestamps (including agenda views using `:timestamp`). The main reason to use a property would be to put it out of the way as far as the user is concerned, instead of right in the heading or right in the body. Another convenient element is that I can do an agenda match on `ORG_GTD_CALENDAR="<today>"` to find only the ones that match today pretty easily (see https://orgmode.org/org.html#Matching-tags-and-properties , relevant bit pasted below.

This also frees up the user to use SCHEDULED and DEADLINE for actually relevant things like "hey on Saturday you have to start this project" or "hey you have to finalize the lunch invites by Wednesday", which right now get merged with "Dentist appointment", and that's not great because it makes the agenda view harder to parse, I think.

... This being said, if orgzly can't use it, I gotta think about something else :)


### org-mode doc blurb
> When matching properties, a number of different operators can be used to test the value of a property. Here is a complex example:

> `+work-boss+PRIORITY="A"+Coffee="unlimited"+Effort<2+With={Sarah\|Denny}+SCHEDULED>="<2008-10-11>"`
> The type of comparison depends on how the comparison value is written:

> - If the comparison value is a plain number, a numerical comparison is done, and the allowed operators are ‘<’, ‘=’, ‘>’, ‘<=’, ‘>=’, and ‘<>’.
> - If the comparison value is enclosed in double-quotes, a string comparison is done, and the same operators are allowed.
> - If the comparison value is enclosed in double-quotes and angular brackets (like ‘DEADLINE<​="<2008-12-24 18:30>"’), both values are assumed to be date/time specifications in the standard Org way, and the comparison is done accordingly. Valid values also include `"<now>"` for now (including time), `"<today>"`, and `"<tomorrow>"` for these days at 0:00 hours, i.e., without a time specification. You can also use strings like `"<+5d>"` or ‘"<-2m>"’ with units ‘d’, ‘w’, ‘m’, and ‘y’ for day, week, month, and year, respectively.
> - If the comparison value is enclosed in curly braces, a regexp match is performed, with ‘=’ meaning that the regexp matches the property value, and ‘<>’ meaning that it does not match.

**Comment by Trevoke** [comment]
Okay so it looks like orgzly does not support timestamps in properties yet.
This means I'll probably implement appointments with a duplicated timestamp - one in properties and one in the heading itself - so I can have the implementation I want while allowing orgzly to also work... And then when orgzly supports the property I can shift away from it.

What do you think?

**Comment by Sinthoras7** [comment]
I mean, if you duplicate the timestamp, it would not be "out of the way as far as the user is concerned". So in principle you could wait until orgzly implements its timestamps in properties, because only then the advantages of handling it this way prevail. But by handling it this way, nobody is worse off, so this can be a good temporary solution :)

**Comment by Trevoke** [comment]
I don't want to wait for orgzly to move away from "SCHEDULED" because I want to provide better agenda views and it's really hard while I'm misusing the planning keywords.
So yeah, I'll deal with the duplicated timestamps and I'll largely assume that people will realize they shouldn't mess with it because it's clearly the time/date they chose so it'll have meaning to them.

**Comment by Trevoke** [comment]
Deferring the agenda view for oopses to #131
