### ISSUE TITLE
Handle Horizon 2 : areas of focus

### ISSUE THREAD

**Issue by Trevoke** [Trevoke/org-gtd.el#119]
Handle horizons.

Might be able to handle something with `org-columns-default-format` - or using CATEGORY for areas of focus.

```
Its value is "%25ITEM %TODO %3PRIORITY %TAGS"

The default column format, if no other format has been defined.
This variable can be set on the per-file basis by inserting a line

#+COLUMNS: %25ITEM .....
```

( also `org-overriding-columns-format` ? )

Have to figure something out for horizons 4 and 5.

**Comment by leo0liver** [comment]
I would love to have this feature as I'm struggling to find balance between my areas of focus.

I've had a go at implementing the areas of focus as you suggested
I added org-set-property function to the process item hook so that I can define each tasks area of focus as a property:
`(setq org-gtd-process-item-hooks '((lambda () (call-interactively #'org-set-property)) org-set-tags-command org-set-effort))`

And then modified the agenda view to show the areas of focus:
`'(("g" "Todays scedule all NEXT items"
     (
      (agenda "" ((org-agenda-span 1)
                  (org-agenda-start-day nil)))
      (todo "NEXT" ((org-agenda-overriding-header "NEXT items")
                    (org-agenda-prefix-format '((todo . " %i %-12:(org-gtd--agenda-prefix-format)")))))
      (todo "WAIT" ((org-agenda-todo-ignore-with-date t)
                    (org-agenda-overriding-header "Delegated/Blocked items")
                    (org-agenda-prefix-format '((todo . " %i %-12 (org-gtd--agenda-prefix-format)"))))))

                ((org-agenda-overriding-columns-format "%TODO %30ITEM %15SCHEDULED %20AREAOFFOCUS %TAGS %5Effort(Effort){:} %6CLOCKSUM")
                (org-agenda-view-columns-initially t)))))`

This works alright but it would be nicer to able to choose from a list of your predefined areas of focus, rather than having to write it out each time you process a task.

**Comment by Trevoke** [comment]
From org-mode manual - 

The display in the agenda buffer looks best if the category is not longer than 10 characters. You can set up icons for category by customizing the `org-agenda-category-icon-alist` variable.

**Comment by Trevoke** [comment]
TODO
- [ ] implement `org-gtd-areas-of-focus` list of strings
- [ ] find that project that created icons for categories and reuse it (if I am not misremembering)
- [ ] let user optionally choose areas of focus as a decoration (provide decoration hook)
- [ ] decide if decoration hook is part of new default hooks or not
- [ ] create agenda views for these areas of focus

**Comment by Trevoke** [comment]
Sample org-agenda-custom-command for area of focus view based on David Allen's designs:

```elisp
(defun stag-skip-unless-foo ()
  (let ((subtree-end (save-excursion (org-end-of-subtree t))))
    (if (and (string-equal "Home" (org-entry-get (point) "CATEGORY"))
             (string-equal "habit" (org-entry-get (point) "STYLE")))
        nil
      subtree-end)))

(with-org-gtd-context
    (let ((org-agenda-custom-commands
           '(("h" "Area of Focus: HOME"
              ((tags "+LEVEL=2+CATEGORY=\"Home\"+ORG_GTD=\"Projects\"")
               (tags "+CATEGORY=\"Home\"+TODO=\"NEXT\"")
               (agenda "" ((org-agenda-skip-function 'stag-skip-unless-foo)
                           (org-agenda-span 1)))
               (tags "+CATEGORY=\"Home\"+STYLE=\"habit\"")
               (tags "+CATEGORY=\"Home\"+ORG_GTD=\"Incubated\""))))))
      (org-agenda nil "h")))
```
