### ISSUE TITLE
Project Templates (enhancement request)

### ISSUE THREAD

**Issue by marabout2015** [Trevoke/org-gtd.el#121]
I have types of projects that repeat. When clarifying an inbox item as a project, I would like to be able to specify a template for its steps.

**Comment by Trevoke** [comment]
That's a neat idea and it makes sense, I've definitely had "same type of project" come up at work and didn't think about making templates.

How do you figure the templates would work? For instance:

1. you are processing an item and you know it's a project
2. you hit a key to choose a template
3. subheadings with preset names appear under the top-level heading you're processing
4. you can edit as you see fit

Or... What is in your head, how do you see it work?

**Comment by marabout2015** [comment]
Thank you. That's the basic functionality I envision. I appreciate the headings. And the ability to just edit them as I see fit is a positive. That sounds like an MVP.
