### ISSUE TITLE
In fresh emacs session can't process inbox without calling capture first

### ISSUE THREAD

**Issue by leo0liver** [Trevoke/org-gtd.el#122]
Hi,

When I open a new emacs session and attempt to call `org-gtd-process-inbox` I get the error `Symbol's function definition is void: org-gtd--inbox-file`. To fix this I have to call org-gtd-capture function and then abort the capture, so that the `org-gtd--inbox-file` variable is defined when I call `org-gtd-process-inbox`.

**Comment by leo0liver** [comment]
I was getting the error when the inbox.org file did exist and had unprocessed items in it. 
But I just found that this was due to doom emacs lazy loading the package, so this issue can be closed :)

**Comment by leo0liver** [comment]
I was getting the error when the inbox.org file did exist and had unprocessed items in it. 
But I just found that this was due to doom emacs lazy loading the package, so this issue can be closed :)

**Comment by Trevoke** [comment]
Well, great that it's fixed!

However, I *should* make the package work with lazy loading. I don't use doom emacs, could you share a minimum config I could use so I can start testing the various paths and making sure they all work through lazy loading?

Thanks!

**Comment by leo0liver** [comment]
I'm new to doom emacs so I think it was actually a mistake on my part. I didnt quite understand how the packaging system worked, and had only added the line: `(package! org-gtd)` to my `DOOMDIR/packages.el` file. To load the package on startup I just had to add the line `(use-package! org-gtd)` to `DOOMDIR/config.el`.
