### ISSUE TITLE
[Suggestion] Create a foldable buffer (similar to org-roam-buffer) to show the horizons 5, 4 and 3. 

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#126]
This is just a summary of [this discussion ](https://discord.com/channels/723999634594201600/911343828433244211/1082666214628802610) in the author's discord.

In the original GTD method, you have [6 horizons to look at](https://gettingthingsdone.com/2011/01/the-6-horizons-of-focus/).

- Ground: Calendar/actions
- Horizon 1: Projects.
- Horizon 2: Areas of focus and accountability.
- Horizon 3: One- to two-year goals and objectives.
- Horizon 4: Three- to five-year vision.
- Horizon 5: Purpose and principles.

`org-gtd` handles the Ground and Horizon 1 already. I think that Horizon 2 will be better handled in version 3 (with some property in the drawer). In some sense, this is related to #119. 

My suggestion is the following, to add a popup-buffer (similar to [`org-roam-buffer`](https://github.com/org-roam/org-roam/blob/main/org-roam-mode.el)) shown while you clarify your items. 

The visualized workflow should be: 

1. Have another file called `horizons.org` (or any name), with headings (it could have text, images, tables, or anything else):
     - Horizon 5
     - Horizon 4
     - Horizon 3

3. While you clarify your items, the new popup-buffer appears. You see your horizons and you plan accordingly.
4. Once you clarify your items, the popup closes. 

More or less, this is a 1-minute mock-up that I did the other day.
 
![image](https://user-images.githubusercontent.com/4078489/230724782-12d8afc8-a33d-4c41-aa03-d17c45f19c6f.png)

Of course, the popup can be called at anytime with a user defined key bind. 

Best.

**Comment by Trevoke** [comment]
TODO:

- [ ] Provide template of the `horizons.org` file with headings for the three/four horizons
- [ ] Provide flag to allow people to choose whether this gets displayed or not
- [ ] MAYBE let the user choose where the buffer goes? (top, left, etc.)

I have to think about which other buffers I may want to display around the clarify buffer as well, but I think this covers it?
