### ISSUE TITLE
wrong-type-argument when using org-gtd-engage

### ISSUE THREAD

**Issue by chubbymomo** [Trevoke/org-gtd.el#136]
Hello! I've started using this package. However, I run into an error when using the function "org-gtd-engage." Below is the full debugger output:

```Debugger entered--Lisp error: (wrong-type-argument arrayp nil)
  replace-regexp-in-string("[[[:digit:]]+/[[:digit:]]+][[:space:]]*" "" nil)
  org-gtd--agenda-prefix-format()
  (org-eval (org-gtd--agenda-prefix-format))
  (format "%-12s" (org-eval (org-gtd--agenda-prefix-format)))
  (format " %s %s" (format "%s" (if (member category-icon '("" nil)) "" (concat category-icon "" (get-text-property 0 'extra-space category-icon)))) (format "%-12s" (org-eval (org-gtd--agenda-prefix-format))))
  org-agenda-format-item("" #("NEXT Look into printing case                      ..." 0 4 (org-stats 0 org-category "org-gtd-tasks" wrap-prefix #("***** " 0 6 (face org-indent)) line-prefix #("**" 0 2 (face org-indent)) face (org-todo org-todo org-level-2) org-todo-head "NEXT" fontified nil) 4 61 (org-stats 0 org-category "org-gtd-tasks" wrap-prefix #("***** " 0 6 (face org-indent)) line-prefix #("**" 0 2 (face org-indent)) face org-level-2 org-todo-head "NEXT" fontified nil) 61 70 (org-stats 0 wrap-prefix #("***** " 0 6 (face org-indent)) line-prefix #("**" 0 2 (face org-indent)) keymap (keymap (follow-link . mouse-face) (mouse-3 . org-find-file-at-mouse) (mouse-2 . org-open-at-mouse)) mouse-face highlight face (org-tag org-level-2) org-todo-head "NEXT" org-category "org-gtd-tasks" fontified nil) 70 71 (org-stats 0 wrap-prefix #("***** " 0 6 (face org-indent)) line-prefix #("**" 0 2 (face org-indent)) rear-nonsticky (mouse-face highlight keymap invisible intangible help-echo org-linked-text htmlize-link) keymap (keymap (follow-link . mouse-face) (mouse-3 . org-find-file-at-mouse) (mouse-2 . org-open-at-mouse)) mouse-face highlight face (org-tag org-level-2) org-todo-head "NEXT" org-category "org-gtd-tasks" fontified nil)) "   " "org-gtd-tasks" ("Keyboard") t)
  org-agenda-get-todos()
  org-agenda-get-day-entries("/home/swilley/Documents/Org/GTD/org-gtd-tasks.org" (4 27 2023) :todo)
  org-todo-list("NEXT")
  #f(compiled-function () #<bytecode -0x4691b0603aa58da>)()
  funcall(#f(compiled-function () #<bytecode -0x4691b0603aa58da>))
  (let ((org-agenda-overriding-header '"All NEXT items") (org-agenda-prefix-format '((todo . " %i %-12:(org-gtd--agenda-prefix-format)")))) (funcall '#f(compiled-function () #<bytecode -0x4691b0603aa58da>)))
  org-agenda-run-series("Scheduled today and all NEXT items" (((agenda "" ((org-agenda-span 1) (org-agenda-start-day nil))) (todo "NEXT" ((org-agenda-overriding-header "All NEXT items") (org-agenda-prefix-format '(...)))) (todo "WAIT" ((org-agenda-todo-ignore-with-date t) (org-agenda-overriding-header "Delegated/Blocked items") (org-agenda-prefix-format '(...)))))))
  org-agenda(nil "g")
  org-gtd-engage()
  funcall-interactively(org-gtd-engage)
  command-execute(org-gtd-engage)
```

Below is my config for org-gtd:

```
  (use-package org-gtd
    :after org
    :config
    (org-edna-mode)
    (setq org-edna-use-inheritance t)
    :custom
    (org-gtd-directory "~/Documents/Org/GTD")
    :bind
    (("C-c c" . org-gtd-choose)
     ("C-c d c" . org-gtd-capture)
     ("C-c d e" . org-gtd-engage)
     ("C-c d a" . org-agenda-list)
     ("C-c d p" . org-gtd-process-inbox)))
```
  
Sorry if I haven't provided enough information. This is my first time creating an issue relating to anything Emacs. Thank you so much for creating this package!

**Comment by Trevoke** [comment]
Hi @chubbymomo , thanks for trying out the package!

Which version of emacs are you using? 27.1 ? 28.2 ? 

How did you install the package?  From melpa? melpa-stable?

**Comment by chubbymomo** [comment]
`GNU Emacs 28.2 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.36, cairo version 1.17.6) of 2023-01-02`

I am unsure how to find which repository it is installed from. Below is the output when I look at the package using the function package-list-packages:

Package org-gtd is installed.

     Status: Installed in ‘org-gtd-20230420.1244/’ (unsigned). Delete
    Version: 20230420.1244
     Commit: a6aca52a7dea498be515ec9fd9285a0dabe01ee5
    Summary: An implementation of GTD.
   Requires: emacs-27.1, org-edna-1.1.2, f-0.20.0, org-9.6, org-agenda-property-1.3.1, transient-0.3.7
    Website: https://github.com/Trevoke/org-gtd.el
 Maintainer: Aldric Giacomoni <trevoke@gmail.com>
     Author: Aldric Giacomoni <trevoke@gmail.com>
Other versions: 20230420.1244 (melpa), 2.3.1 (melpa-stable).

This package tries to replicate as closely as possible the GTD workflow.
This package assumes familiarity with GTD.

This package provides a system that allows you to capture incoming things
into an inbox, then process the inbox and categorize each item based on the
GTD categories.  It leverages org-agenda to show today's items as well as the
NEXT items.  It also has a simple project management system, which currently
assumes all tasks in a project are sequential.

For a comprehensive instruction manual, see the documentation.
Either the info file or in the doc/ directory of the repository.
Upgrade information is also available therein.

I have both melpa and melpa-stable setup, however.

**Comment by Trevoke** [comment]
Could I get a sense of what's around this "NEXT look into printing case" item? Or, if you can, can you share a possibly anonymized version of the state of your GTD files?

**Comment by chubbymomo** [comment]
Sure, I've just started using this package, so there's little to be anonymized.

```
#+STARTUP: overview indent align inlineimages hidestars logdone logrepeat logreschedule logredeadline
#+TODO: NEXT(n) TODO(t) WAIT(w@) | DONE(d) CNCL(c@)

* Actions
:PROPERTIES:
:ORG_GTD: Actions
:END:
** NEXT Get humidifier                                      :Storage:Health:
[2023-04-23 Sun 17:38]

** NEXT Find humidifier
[2023-04-27 Thu 12:17]
* Projects
:PROPERTIES:
:TRIGGER: relatives(forward-no-wrap todo-only 1 no-sort) todo!(NEXT)
:ORG_GTD: Projects
:END:
** Keyboard [0/4]                                                 :Keyboard:
[2023-04-27 Thu 12:25]
*** NEXT Look into printing case                                 :Keyboard:
*** TODO Look into soldering                                     :Keyboard:
*** TODO Look at purchasing key switches                         :Keyboard:
*** TODO Look at purchasing PCB                                  :Keyboard:
```

Sorry, I couldn't upload the .org file.

**Comment by Trevoke** [comment]
Hmm, I'm struggling to replicate this. A few additional questions:

1. Have you tried restarting emacs? this is sometimes necessary if you have
just upgraded org-mode.
2. Have you tried killing the buffer for the agenda as well as the buffer
for the `org-gtd-tasks.org` file, then trying to summon the agenda again?
(this may currently be necessary if you're just getting started, though I
don't think it is)
3. Are you using doom emacs, spacemacs, or anything like that?

**Comment by chubbymomo** [comment]
Sorry for the late answer:

1. Yes.
2. Yes.
3. No, I rolled the config myself.

**Comment by Trevoke** [comment]
Okay, so, the problem is:

`  replace-regexp-in-string("[[[:digit:]]+/[[:digit:]]+][[:space:]]*" "" nil)`
The `nil` in there should be a string where we replace the stat cookie (e.g. `[3/6]`)
It's happening on this line https://github.com/Trevoke/org-gtd.el/blob/master/org-gtd-customize.el#L164

This line depends on a feature from org 9.6.

Try to add the following two lines to your configuration, prior to any line requiring org-mode:

```
(assq-delete-all 'org package--builtins)
(assq-delete-all 'org package--builtin-versions)
```

Then restart emacs and tell me if this helps?

**Comment by chubbymomo** [comment]
I figured it out (Well, you did for me. Lol)! I checked my version of org was out of date... I'm so sorry for wasting your time on this. I had been following the years-old "Emacs From Scratch" tutorials until recently. So, I ended up using the outdated Org repository. I changed that, and after some fiddling around and changing my package system to straight.el it now works!
