### ISSUE TITLE
Troubles after Updating Org Package

### ISSUE THREAD

**Issue by LewWadoo** [Trevoke/org-gtd.el#137]
I am currently using Emacs 28.1 on Ubuntu with the built-in version 9.5.2 of the Org package. After installing `org-gtd` and `org` as its dependency, I encountered an issue whereby Emacs fails to run certain commands in my configuration files. The error message indicates that the function `org-assert-version` cannot be located. To resolve this issue, I attempted to comment out other commands such as `(require 'ob-*(any language here))` but soon realized that I could not even build an *Org Agenda* for anything.

As a result, I am seeking guidance on how to troubleshoot this issue. I have not been able to use your package as it currently breaks my Emacs setup. Could you kindly provide some assistance on this matter? Thank you.

**Comment by Trevoke** [comment]
Hello!

If you have just upgraded org-mode (org-gtd requires org 9.6) then you
probably also need to restart emacs. org-mode is a very large beast and
does not handle its upgrades particularly gracefully.

In my own config, I have to tell emacs to forget that it knows about
org-mode : https://github.com/Trevoke/.emacs.d/blob/master/init.el#L33

It hadn't occurred to me that this might be something I have to add to the
configuration documentation; could you please try these two
`assq-delete-all` lines in your own config, prior to `org-mode` being
required or loaded, and tell me if this makes a difference for you?

**Comment by LewWadoo** [comment]
I added these 3 lines from your config before any lines that cause errors:
```emacs lisp
(assq-delete-all 'org package--builtins)
(assq-delete-all 'org package--builtin-versions)
(require 'org)
```
But I still get this error after installing `org-gtd` and rebooting Emacs:
```
Debugger entered--Lisp error: (invalid-function org-assert-version)
  org-assert-version()
  byte-code("\300\301!\210\302 \210\300\303!\210\300\304!\207" [require org-macs org-assert-version cl-lib oc] 2)
  require(org-keys)
  eval-buffer(#<buffer  *load*-15400> nil "/home/eugene/.emacs.d/elpa/org-9.6.5/org.el" nil t)  ; Reading at buffer position 3557
  load-with-code-conversion("/home/eugene/.emacs.d/elpa/org-9.6.5/org.el" "/home/eugene/.emacs.d/elpa/org-9.6.5/org.el" nil t)
  require(org)
  eval-buffer(#<buffer  *load*> nil "/home/eugene/.emacs" nil t)  ; Reading at buffer position 1457
  load-with-code-conversion("/home/eugene/.emacs" "/home/eugene/.emacs" t t)
  load("~/.emacs" noerror nomessage)
  startup--load-user-init-file(#f(compiled-function () #<bytecode -0xae1bdd5a5fbc3ec>) #f(compiled-function () #<bytecode -0x1f3c686ddc0ca9b5>) t)
  command-line()
  normal-top-level()
```

**Comment by chubbymomo** [comment]
Hey, @LewWadoo. I just ran into this issue hours ago. It doesn't _really_ have anything to do with org-gtd. It's your updating Org that caused the issue. I saw online that the solution is to remove the Org Elpa repository if needed. Then, you must delete the Org package's directory in <your config location>/elpa/<org directory>. Finally, you need to install Org through the GNU Elpa repository. I think following those steps should fix your issue. Though, for some reason, I couldn't bypass the error after doing those steps, as others had mentioned. What truly fixed the error was switching to using straight.el as my package management solution. By doing that, everything was freshly installed again, including Org, and it worked perfectly from there! If that isn't a suitable solution for you, below is the discussion I mentioned earlier that helped people fix the error you're getting:

https://www.reddit.com/r/emacs/comments/zd3l7p/org_mode_elpa_intall_invalid_function/

Though I must say, even being new to Emacs, switching to straight.el was easy, and it seems more "stable" to me. If you need any assistance, please don't hesitate to @ me!

**Comment by Trevoke** [comment]
Hi @LewWadoo , is this still a problem for you?

**Comment by LewWadoo** [comment]
Thank you for your response, Trevoke!

I would love to try to and leave a reply here, but unfortunately, I am not
going to have time soon for that. You are free to close the issue. Anyway,
I have no idea what version I will try the next time I have a spare time
for that.

**Comment by Trevoke** [comment]
Alright - I am closing the issue, then. Sorry you had trouble with org-mode - I also spent too many hours dealing with that problem, so I empathize. And good luck with your next task management attempt :)
