### ISSUE TITLE
Popup interface inscreenshot removed?

### ISSUE THREAD

**Issue by doolio** [Trevoke/org-gtd.el#14]
When I decide to process my inbox I don't see the multiple choice popup as per [ogpi-1.png](https://github.com/Trevoke/org-gtd.el/blob/master/doc/ogpi-1.png). I only see tho options in the minibuffer. Is this just a case of the README being out of date.

**Comment by Trevoke** [comment]
If you use `C-h` when you see the options in the minibuffer, the help window will pop up - that might be worth clarifying in the readme as well :)
