### ISSUE TITLE
In 3.0beta, `org-gtd-trash` fails to find the function `with-org-gtd-context`

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#141]
Hi! 

I wanted to trash some items in the clarify buffer, and I found this bug. 

![image](https://user-images.githubusercontent.com/4078489/236633465-df221db3-e13e-436c-98db-e19c6367272f.png)

The complete trace back is here. 

```
Debugger entered--Lisp error: (invalid-function with-org-gtd-context)
  with-org-gtd-context(nil)
  org-gtd-trash--apply()
  org-gtd-organize--call(org-gtd-trash--apply)
  #<subr org-gtd-trash>()
  apply(#<subr org-gtd-trash> nil)
  #f(compiled-function (fn &rest args) #<bytecode 0x1397d546238098c9>)(#<subr org-gtd-trash>)
  apply(#f(compiled-function (fn &rest args) #<bytecode 0x1397d546238098c9>) #<subr org-gtd-trash> nil)
  (lambda (fn &rest args) (interactive #f(compiled-function (spec) #<bytecode -0x18a5412c612edd3c>)) (apply '#f(compiled-function (fn &rest args) #<bytecode 0x1397d546238098c9>) fn args))(#<subr org-gtd-trash>)
  apply((lambda (fn &rest args) (interactive #f(compiled-function (spec) #<bytecode -0x18a5412c612edd3c>)) (apply '#f(compiled-function (fn &rest args) #<bytecode 0x1397d546238098c9>) fn args)) #<subr org-gtd-trash> nil)
  org-gtd-trash()
  funcall-interactively(org-gtd-trash)
  command-execute(org-gtd-trash)
```

Thanks.

**Comment by maikol-solis** [comment]
Following the same logic as https://github.com/Trevoke/org-gtd.el/blob/org-gtd-3/org-gtd-knowledge.el, my best guess is there is missing something like 

```
(require 'org-gtd-core)
(require 'org-gtd-archive)
```

at the top of https://github.com/Trevoke/org-gtd.el/blob/org-gtd-3/org-gtd-trash.el

**Comment by Trevoke** [comment]
I think you're right, good call, let me play with this a little and make sure the autoloads do work correctly.

**Comment by Trevoke** [comment]
Okay, I think this part, at least, should be a lot cleaner now :D

**Comment by Trevoke** [comment]
I'll wait for your confirmation to close this, because our systems are different :)

**Comment by maikol-solis** [comment]
Now it works perfectly. Thanks.
