### ISSUE TITLE
Make `org-gtd-set-area-of-focus` interactive

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#144]
I'm trying to set up my key binds in doom and I found useful to call `org-gtd-set-area-of-focus`, when I need to change some category in my projects. However, in the `map!` command, it does not work because it isn't interactive. 

This is my config so far. 

```
(map!
   (:map org-gtd-clarify-map
    :desc "Organize item"         "C-c C-c" #'org-gtd-organize)
   :leader
   :prefix ("d" . "org-gtd")
   :desc "Capture"                 "c" #'org-gtd-capture
   :desc "Engage"                  "e" #'org-gtd-engage
   :desc "Horizons"                "h" #'org-gtd-clarify-toggle-horizons-window
   :desc "Process inbox"           "p" #'org-gtd-process-inbox
   :desc "Show all next"           "n" #'org-gtd-show-all-next
   :desc "Archive items"           "a" #'org-gtd-archive-completed-items
   :desc "Send to Google Calendar" "g" #'org-gcal-post-at-point
   (:prefix ("r" . "review")
    :desc "Areas of Focus"         "f" #'org-gtd-review-area-of-focus
    :desc "Stuck Projects"         "s" #'org-gtd-review-stuck-projects
    :desc "Incubated"              "i" #'org-gtd-review-stuck-incubated-items)
   (:prefix ("s" . "set")
    :desc "Set area of focus"      "a" #'org-gtd-set-area-of-focus))
 ```

**Comment by Trevoke** [comment]
Hi!

This function is intended to be used as an organize-hook, e.g. `(setq org-gtd-organize-hooks '(org-gtd-set-area-of-focus))`. It's not interactive because it has a filter for when it will actually run, which may or may not behave the way you want it to. 

You do highlight that people who have existing GTD data will probably want to update their data with areas of focus, so I'll add an interactive function!

**Comment by maikol-solis** [comment]
> You do highlight that people who have existing GTD data will probably want to update their data with areas of focus, so I'll add an interactive function!

Yes, this is exactly my use case. These days I was reviewing my pending tasks and noticed that none has the area of focus category. I noticed that calling this function was the solution. However it was a little uncomfortable without a proper keybind, and I had to call it directly from the minibuffer.

**Comment by Trevoke** [comment]
I've just pushed a change including `org-gtd-area-of-focus-set-on-item-at-point` which should do what you need.

Someday I'll figure out how to do something like this and keep small function names.
