### ISSUE TITLE
Change column widths in the agenda?

### ISSUE THREAD

**Issue by pdxmph** [Trevoke/org-gtd.el#149]
Looking at the agenda produced by `org-gtd-engage`, I'd like to expand the first column, with the title of the project (in the case of projects). Right now it's a little narrow, but the todo titles have a ton of space. Is there a way to do this without forking/patching `org-gtd-agenda.el` (which I _think_ is where this is handled?)

I tried to just set the standard `org-agenda-prefix-format` but nothing doing.

**Comment by pdxmph** [comment]
Thanks for the response. :-\ I wonder if the way to come at it, then, is to take a "breadcrumb" approach within the item titles themselves. One thing I sort of struggle with is the lack of context for items (not gtd @contexts, but rather project or list contexts). 

I tend to write subtasks in a very terse style, so when they turn up in a list it's not always easy to remember what I'm talking about,  especially if I'm doing gtd right and trusting the system to remember. 

Because of this limitation in that leading column I've taken to rewriting my top-level headings to provide more of a hint in the first word or two. There's a ton of real estate in the heading section of the agenda, though. 

This is on my mind because I've been trying to use Beorg for mobile capture and also to check my @errands list on the go, and I was happy to note that it provides project context in its TODO lists.

**Comment by Trevoke** [comment]
*nod* I believe we might be able to use an agenda display filter to adjust how the item is displayed.

This being said, depending on where you want your eyes to be to get the information, org-agenda *does* provide a breadcrumb already, with `org-agenda-show-outline-path` : 

> Non-nil means show outline path in echo area after line motion.
> 
> If set to ‘title’, show outline path with prepended document title.  Fallback to file name is no title is present.

**Comment by dmgerman** [comment]
Implemented in #154 

The width was hardcoded in the org-agenda-engage

**Comment by Trevoke** [comment]
Well I'm really confused because I tried this and couldn't get it to work. Either way, thanks! Putting other comments in the PR itself.

**Comment by dmgerman** [comment]
I suspect that it was because you were getting an invalid parameter stringp error. 

I think this macro checks the types of the parameters _before_ it gets expanded. This should be considered a bug, so the ,(eval ) does the evaluation before the macro gets called.

**Comment by Trevoke** [comment]
No errors whatsoever. It worked like a charm. It just didn't change the width.

**Comment by Trevoke** [comment]
This is now in the unstable release, thanks @pdxmph for opening the issue, thanks @dmgerman for the work!
