### ISSUE TITLE
org-gtd--nextify: Wrong number of arguments: nil, 0

### ISSUE THREAD

**Issue by jsandovalc** [Trevoke/org-gtd.el#16]
Hi,

Your project catched my attention a while ago and now that it's in melpa i decided to give it a try. I've been implementing GTD in emacs in a more manual way.

I'm trying to set an inbox entry as a project with p, so I press `p`, then `C-c x` and it asks for `tags`. I write a couple for the project and after hitting `RET` I'm getting the following error:
```
org-gtd--nextify: Wrong number of arguments: nil, 0
```

Not sure if I'm doing something wrong, or maybe something in my config. ¿Any idea of why?

Thanks for the interesting project.

**Comment by Trevoke** [comment]
Hi!

I should probably make that code path slightly more resilient.

The project should look something like this:

![image](https://user-images.githubusercontent.com/67913/89963973-0be2e880-dc17-11ea-8a83-9fa109bedfb5.png)

What does the project look like when you set it up? I'm _guessing_ it looks like this instead:
![image](https://user-images.githubusercontent.com/67913/89964166-6714db00-dc17-11ea-8440-bca79500f406.png)

**Comment by jsandovalc** [comment]
@Trevoke Yes, it lookls like that. 

I created the subtasks and it worked. :smiley: 

BTW in your screenshots, I can see a `*` followed by the bullet. I see it weirdly too using the spacemacs-theme.

Thanks for your help. I hope to introduce `org-gtd.el` in my workflow. It looks very promising.

**Comment by Trevoke** [comment]
The readme is not as clear as it could be, I have to do some work on it.

Yeah, the `*` is visible for a few reasons, it's .. Part of how I have org-mode configured. I think technically that's a bug, but I don't care enough :)

**Comment by Trevoke** [comment]
And it's my pleasure, thank you for your interest in the package!

**Comment by maikol-solis** [comment]
> Hi!
> 
> I should probably make that code path slightly more resilient.
> 
> The project should look something like this:
> 
> ![image](https://user-images.githubusercontent.com/67913/89963973-0be2e880-dc17-11ea-8a83-9fa109bedfb5.png)
> 
> What does the project look like when you set it up? I'm _guessing_ it looks like this instead:
> ![image](https://user-images.githubusercontent.com/67913/89964166-6714db00-dc17-11ea-8440-bca79500f406.png)

Hi! 
I have the same problem (capture + processing + ask for tags + nextify error)  but I can't see any file with project heading or anything. Where should I look at? 

Thanks for the help. This project looks awesome.

**Comment by maikol-solis** [comment]
Checking with `emacs --debug-init` I got this 

```
  signal(wrong-number-of-arguments ((first-entry . rest-entries) 0))
  org-gtd--nextify()
  org-gtd--project()
  org-gtd--process-inbox-element()
  #f(compiled-function () #<bytecode 0x3a8bc45>)()
  org-scan-tags(#f(compiled-function () #<bytecode 0x3a8bc45>) t nil nil)
  org-map-entries(#f(compiled-function () #<bytecode 0x3a8bc45>))
  org-gtd-process-inbox()
  funcall-interactively(org-gtd-process-inbox)
  call-interactively(org-gtd-process-inbox nil nil)
  command-execute(org-gtd-process-inbox)
```

**Comment by Trevoke** [comment]
Hi @maikol-solis , is this the same issue as #23 ?

**Comment by maikol-solis** [comment]
Yes it does. Sorry for the noise in a closed issue. I thought that I found another bug.

**Comment by Trevoke** [comment]
@maikol-solis no worries - I really need to make the readme better :)
