### ISSUE TITLE
org-gtd-engage thinks any text with a slash (/) in it is a directory

### ISSUE THREAD

**Issue by thancock20** [Trevoke/org-gtd.el#188]
Whenever I run `org-gtd-engage` I get a message like the following for every slash (/) in the `org-gtd-tasks.org` file:
`Directory '/home/todd/org/** Catch up on MCU [0/' does not exist! Create it? (y or n)`

This particular example is in the cookie on a project name, but it also happens for all the URLs as well. It also happens when I run `org-gtd-engage-grouped-by-context`.

The issue does not occur when I open `org-agenda`  to either the weekly view or the todos view while `org-gtd-mode` is enabled.

I'm using org-gtd with Doom Emacs on Arch Linux.

**Comment by thancock20** [comment]
I figured it out. I had set `org-agenda-files` to `org-gtd-tasks.org` in my configuration. Removing that line fixed the issue.

**Comment by Trevoke** [comment]
Oh that makes sense, good find and good debugging!

--

Aldric.
