### ISSUE TITLE
Nothing added to agenda

### ISSUE THREAD

**Issue by frankxzhang** [Trevoke/org-gtd.el#19]
Hi,

Thanks for the package. When I tried the packages, it seems everything works fine, but after processed my inbox, but nothing shows up on my agenda view, also when I try Ctrl-c d n, nothing shows up also. I am using doom emacs on macOS and I am using the configuration from the end of document of this package. Do you have any idea? Thank you.

**Comment by frankxzhang** [comment]
Thank you guys. The problem was solved by open the actionable.org file in my gtd folder, and then press Ctrl-c [ to add it to agenda manually. But also I tried to install it on another Windows 10 computer installed with emacs from Ubuntu 20.04 via wsl2, it worked immediately after I installed org-gtd. Just don't know why.

**Comment by frankxzhang** [comment]
Also, for the default setting, I have to delete the line of " :pin melpa-stable " and add ":custom"  before the line of "(org-agenda-files `(,org-gtd-directory))" to make it work for me.

**Comment by Trevoke** [comment]
Thanks for reporting this and finding a fix for your system. I will explore this and find ways to make this reliable.
