### ISSUE TITLE
org-gtd-engage-grouped-by-context function uses tags not prefixed @.

### ISSUE THREAD

**Issue by yjtknst** [Trevoke/org-gtd.el#191]
I think the org-gtd-engage-grouped-by-context function is a very useful implementation. I appreciate it. The only problem is that although the function documentation says that context tags are those prefixed @, the function uses all tags including those do not start with @. This causes the ATTACH tag to be listed as a context item.

**Comment by Trevoke** [comment]
Strange. Can you show me an example heading that shows up when it shouldn't ?

**Comment by yjtknst** [comment]
Sorry, I checked the org-gtd-tasks file myself and solved the problem. I realized that I had accidentally put an ATTACH tag on the Projects entry (the top level Projects, not the individual project headings), and when I removed it, the ATTACH tag was no longer picked up.

**Comment by Trevoke** [comment]
No worries! org-mode is a powerful and complicated beast :)
