### ISSUE TITLE
Make org-gtd-done accept multi todo keyword

### ISSUE THREAD

**Issue by dev590t** [Trevoke/org-gtd.el#197]
My personal org-todo-keywords is
`(sequence "TODO(t)" "NEXT(n)" "RUNNING(r)" "WAIT(w@)" "|" "DONE(d)" "FAIL(f@)" "CANCEL")`

I want to switch to workflow of `org-gtd`. I would like integrate `org-gtd` workflow to my current data.  Unfortunaly, `org-gtd-done` allow choose only 1 todo keyword as DONE stat. I need choose `DONE` and `FAIL` as DONE stat : `(org-gtd-done "DONE" "FAIL")`, else `(setq org-agenda-skip-scheduled-if-done t)` will not filter FAIL tasks.

Did it is possible to add feature? Else new incomer should rewrite all org file 's todo keywords to switch to `org-gtd`. It is very time consuming.

**Comment by Trevoke** [comment]
Hi! 
The feature can be added, of course. Before I do so, I'd like to have a sense of the need. Org-gtd is at a point where it is _almost but not quite_ beginning to  reimplement org-mode, so I would like to be careful with what I do add: when possible, I'd rather defer back to org-mode behavior directly

For me, I add a log note when things are canceled so I can keep a record of why this got canceled - so for me, FAIL and CNCL are the same keyword.

Why do you need all three of them? How does your workflow change between DONE, FAIL, and CANCEL?

**Comment by dev590t** [comment]
Hi,

>For me, I add a log note when things are canceled so I can keep a record of why this got canceled - so for me, FAIL and CNCL are the same keyword.

>Why do you need all three of them? How does your workflow change between DONE, FAIL, and CANCEL?

I think this feature is usefull no just for integrate my workflow to org-gtd. I think that is usefull in general case. FAIL should considered as DONE or CNCL in org-gtd is not really matter to me. I just want org-gtd can interprete FAIL keyword, else (setq org-agenda-skip-scheduled-if-done t) will not filter FAIL tasks in `org-gtd-engage`.

To integrate my current data to org-gtd, exists 2 solutions:
1) convert the set of todo keywords to org-gtd todo keywords in org file.
2) org-gtd-done or org-gtd-cancel accept few todo keywords.

I prefer the second solutions:

Imagine I work in team, we use jira for the project management, the todo keyword in Jira is:  TODO, FAIL,DONE,CANCEL. I use org-jira for the synchronisation, the data of Jira is download and compile to a org file, then I use org-gtd for the task management on this org file.
In this case, I can't modify todo keyword into org-gtd todo keyword, because the org file data is shared because the team.
Without this feature, collaboration is complicated. (notice: I'm not a Jira and org-jira user, my example maybe is wrong, I just want show this feature is usefull for collaboration with a fictif example)

The above example is fictif, and not concern me currently. My real problem currently is that in my org mode system, FAIL don't have the exact same meaning than DONE or CNCL. FAIL mean a task I finish execution, but no give the expected result. If I have a elisp function, the behavior between FAIL,DONE,CNCL task is also different.
If I use the fist solution, and translate of FAIL into DONE or CNCL, my system will be broken. A simple translation isn't enough. I should write a advanced elisp function that translate FAIL into DONE, and save the information the task is success or fail in PROPERTIES. Then update all elisp function to get the information that task is success or fail from PROPERTIES. 
This solution is very complex, and I'm not a elisp programmer, I can't write such advanced function.

You can see this feature will allow to use org-gtd almost with any workflow without broken the initiale system of data.
