### ISSUE TITLE
Trying to process a item gives (wrong-number-of-arguments (first-entry . rest-entries) 0)

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#23]
If I try to process an item to a new project and after setting the tags it throws me this error (I used `emacs --debug-init`) and can't continue and the screen stays blocked. 

```
Debugger entered--Lisp error: (wrong-number-of-arguments (first-entry . rest-entries) 0)
  signal(wrong-number-of-arguments ((first-entry . rest-entries) 0))
  org-gtd--nextify()
  org-gtd--project()
  org-gtd--process-inbox-element()
  #f(compiled-function () #<bytecode 0x3a8bc45>)()
  org-scan-tags(#f(compiled-function () #<bytecode 0x3a8bc45>) t nil nil)
  org-map-entries(#f(compiled-function () #<bytecode 0x3a8bc45>))
  org-gtd-process-inbox()
  funcall-interactively(org-gtd-process-inbox)
  call-interactively(org-gtd-process-inbox nil nil)
  command-execute(org-gtd-process-inbox)
```

Thanks for the help.

**Comment by Trevoke** [comment]
Thanks for the report! I have one question for you, which is -- what does the project look like when you try to submit it? It should look something like this:

```
* Project title
** First action
** Second action
** Third action
```

Please show me the structure -- and after that we may have to go bug-hunting :)

**Comment by maikol-solis** [comment]
Hi @Trevoke. For the moment I started to try `org-gtd` in a fresh folder. There is only one file `inbox.org` and `actionable.org`. 

The latter have this structure, 


```
#+STARTUP: overview indent align inlineimages hidestars logdone logrepeat logreschedule logredeadline
#+TODO: NEXT(n) TODO(t) WAIT(w@) | DONE(d) CANCELED(c@)

* Actions
:PROPERTIES:
:CATEGORY: Action
:END:

* Delegated
:PROPERTIES:
:CATEGORY: Delegated
:END:


* Scheduled
:PROPERTIES:
:CATEGORY: Scheduled
:END:



* Projects
:PROPERTIES:
:TRIGGER: next-sibling todo!(NEXT)
:CATEGORY: Projects
:END:

```

Thanks for the help

**Comment by Trevoke** [comment]
Yes - I'm sorry, I didn't ask the question well.

The process goes like this:

1. First you capture something into the inbox
2. Then you process the entire inbox

For each item in the inbox, you decide what you will do with the item. You have decided that this particular item would be a project (which is to say, you hit `p` when asked what to do with the item). I know this because the code snippet you showed has `org-gtd--project` in it.

This means that when processing the item, you first had:

```
* whatever you have entered as an inbox item here
[2020-11-28 Sat 09:35]
```

**My question is, what did you do to this item before hitting `C-c c` ?**

The reason I ask is because, before you hit `C-c c`, if you have chosen a project, you should have something like this:

```
* Project title
** First action
** Second action
** Third action
```

This way, when you hit `C-c c`, you get to add a tag, and when you press enter, it'll go to the action file, which will look like this (I am only showing the Projects subsection):

```
* Projects
:PROPERTIES:
:TRIGGER: next-sibling todo!(NEXT)
:CATEGORY: Projects
:END:
** Project title                                                     :mytag:
- Refiled on [2020-11-28 Sat 09:40]
*** NEXT First action
*** TODO Second action
*** TODO Third action
```

**Comment by maikol-solis** [comment]
Don't worry. Maybe I didn't understand you correctly. 

> For each item in the inbox, you decide what you will do with the item. You have decided that this particular item would be a project (which is to say, you hit `p` when asked what to do with the item). I know this because the code snippet you showed has `org-gtd--project` in it.
> 
> This means that when processing the item, you first had:
> 
> ```
> * whatever you have entered as an inbox item here
> [2020-11-28 Sat 09:35]
> ```

I have this part exactly as yours. 


> **My question is, what did you do to this item before hitting `C-c c` ?**
> 
> The reason I ask is because, before you hit `C-c c`, if you have chosen a project, you should have something like this:
> 
> ```
> * Project title
> ** First action
> ** Second action
> ** Third action
> ```

Here after press `p` (project) only this is shown. The prompt doesn't offer where to put this item 
```
Clarify buffer. Finish 'C-c c'
* My new item
[2020-11-28 Sat 08:52]
```

After that the buffer get stuck and I can't continue. 

Maybe here is the problem.

**Comment by Trevoke** [comment]
I see.

When you press `p`, you find yourself in the edit buffer, with `Clarify
buffer. Finish `C-c c`.

At this point, make the changes you need:

* My new item
** First action
** Second action
** Third action



Once you have done this, hit `C-c `, then choose tags and press Enter.

**Comment by maikol-solis** [comment]
Oh I see it! I just understood how does it work. 

In this case `My new item` is the project's title and I have to include all the tasks inside the project. 

Now, what happens if I already have a project and I want to include more actions inside 

For example, before I press `C-c c` I type  

```
* My new cool project 
** First task 
** Second task  
```

And afterwards I capture a new item called "Third task" and I want it to be inside the project. How do I achieve this?

**Comment by Trevoke** [comment]
@maikol-solis ah, yes, good question!

In the `org-gtd-directory` path, there are three files:

- inbox.org
- actionable.org
- incubate.org

Projects go into the actionable.org file, so you can go there to do the edit yourself. This package currently does not have a clean way to "add to an existing project from the inbox", so I might suggest choosing to make it a quick action, or choosing to throw it away, or even marking it as a reference, and then editing the project that way.

I could work to implement a "add to existing project" flow - based on what I currently understand, it would be a lot of complex work for an overall small reward (for instance, I don't know how I would help you place the new action in the correct sequence in the project).
Come to think of it, if I implement the org-linker-edna as the backbone of the linked projects, it might not matter in which order the actions are -- but it might also increase the complexity of the abstraction leak when creating a project ( https://github.com/toshism/org-linker-edna ), so I perceive a heavy tradeoff.

**Comment by maikol-solis** [comment]
> @maikol-solis ah, yes, good question!
> 
> In the `org-gtd-directory` path, there are three files:
> 
>     * inbox.org
> 
>     * actionable.org
> 
>     * incubate.org
> 
> 
> Projects go into the actionable.org file, so you can go there to do the edit yourself. This package currently does not have a clean way to "add to an existing project from the inbox", so I might suggest choosing to make it a quick action, or choosing to throw it away, or even marking it as a reference, and then editing the project that way.

Thanks for the explanation. Very insightful. In my case, if I have in the inbox  "Third task" and choose quick action or throw it away, it will be archived. I think it's better selected like "single action" and refile it later. 


> I could work to implement a "add to existing project" flow - based on what I currently understand, it would be a lot of complex work for an overall small reward (for instance, I don't know how I would help you place the new action in the correct sequence in the project).

I know little about lisp, but maybe a simple `org-refile` can do the work. I think the task can go at the end of the project list and the user should to put them in order according to his expectations or plans. This way you don't have to program some complex code only to put everything in order. 

> Come to think of it, if I implement the org-linker-edna as the backbone of the linked projects, it might not matter in which order the actions are -- but it might also increase the complexity of the abstraction leak when creating a project ( https://github.com/toshism/org-linker-edna ), so I perceive a heavy tradeoff.

I like your approach to have projects with sequential defined steps. I think that this is a feature instead of a bug in your implementation. In the long run, the user has to think better how to organize their projects to being actionable instead of having a pile of "NEXT" actions in the same project (it happens to me). 

Referring to  #16, I think that the key to understand the package is the README. I will give a serious opportunity to this package because now I understand how does it work thanks to this conversation. 

Thanks for your patience. 

Best.
