### ISSUE TITLE
How did you include org-roam in the "archive" option?

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#24]
Watching your talk in EmacsConf 2020 https://emacsconf.org/2020/talks/11/ (great talk by the way), you used `org-roam` to archive the items that you want to transform later in a note (inside the `org-roam-directory` I guess). 

I was trying to replicate this with the current version of `org-gtd` (4716603f3719acd89a268fb907b91fd3d6af311a) and I only get that the item get archived into  `inbox.org_archive`. 

Could you please share the config you used or point me about something that I haven't done to replicate this behavior with the "archive" option?

Thanks.

**Comment by Trevoke** [comment]
Hi!

There is no automatic connection between org-gtd and org-roam right now.
One reason is that I don't want to enforce a dependency on org-roam if
that's not how you want to store your knowledge.

What I did in the talk is:

1. while processing the item, choose "reference"
2. manually open org-roam and add the information
3. finish the org-roam capture
4. go back to the inbox processing buffer and finish with `C-c c`

**Comment by maikol-solis** [comment]
Oh, I see it! I get lost in the talk, but it has totally sense now. 
I will replicate your workflow with items I want to archive. 
Thank you very much for the explanation.

**Comment by Trevoke** [comment]
Of course! May I close this issue?

**Comment by maikol-solis** [comment]
Yes of course! Thanks for your time!.  Best.
