### ISSUE TITLE
How do I could return to the popup options if I changed my mind about how to process an item?

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#25]
For example, 

I have this item in my inbox.org

`* One great item`

I process the inbox and choose "quick action" and a dedicated buffer appears to clarify the item. While I'm clarifying this, I decided that maybe the item is a project or belongs to an existing project. 

How do I could return to the previous state and select for example "project" instead of "quick action"? 

Thanks again.

**Comment by Trevoke** [comment]
Hi! right now that is not possible, but it's certainly a good idea! Marking this as an enhancement.

**Comment by Trevoke** [comment]
In 2.0 the flow changed and now you clarify the item before you make the choice -- it is also easier to go back to clarifying the item when the choice menu appears.

**Comment by maikol-solis** [comment]
Thanks!
