### ISSUE TITLE
can't categorize an item as project

### ISSUE THREAD

**Issue by guoweis** [Trevoke/org-gtd.el#28]
keep hitting 
```
org-gtd--nextify: Wrong number of arguments: (first-entry . rest-entries), 0
```

This doesn't happen for delegate

**Comment by guoweis** [comment]
oh, this must be because if it's a project, it must have at least one TODO?

**Comment by Trevoke** [comment]
Hi!

Projects look like this when you prepare them:

```
* Project name
** First action
** Second action
** etc. until the last action
```

I need to make this more clear, it's in the readme but it's not obvious.
