### ISSUE TITLE
when I tried "incubate", it complains `user-error: No refile targets`

### ISSUE THREAD

**Issue by guoweis** [Trevoke/org-gtd.el#29]
I thought this should go to incubate.org?

**Comment by guoweis** [comment]
i'm hitting this error here 
https://github.com/bzg/org-mode/blame/master/lisp/org-refile.el#L599

**Comment by zylinski** [comment]
You need to manually add categories into `incubate.org`. for example:

```
* health
* reading
* financial
```

Don't forget to reload.

**Comment by Trevoke** [comment]
Hello!

I am taking care of this through an addition to the README that explains this requirement, as well as the addition of a default incubation top-level headline to the auto-generated incubate file. My apologies for leaving this out! Please reopen this if the problem isn't solved for you.
