### ISSUE TITLE
org-cature templates return nil error

### ISSUE THREAD

**Issue by poulpoulsen** [Trevoke/org-gtd.el#3]
hello,
i'm interested in your favorite program, but unfortunately there seems to be an error with the templates.
i copy and paste the lines from the documentation, but after pressing C-c d c i or l there is an file expansion error inside the org-templates.
my org-gtd-directory is set,
there is an inbox.org file inside.
i think the synthax is anyhow not fully correct.
i use emacs 26.3 on linux kubuntu with org 9.3. 
any clues?

Regards
Poul

**Comment by Trevoke** [comment]
Hi! Thanks for trying this out. 

Could you tell me what the error is?

**Comment by poulpoulsen** [comment]
hello,
yes sure.
the message is:
org-capture-expand-file: Invalid file location: nil

(org-gtd--path org-gtd-inbox-file-basename) evals to 
"/home/held/org-rep/gtd/inbox.org"
that looks good.

Fortunately i found the error:
Due to changes in Org-mode 9.2 (found inside the release notes) your template code is not valid anymore.
Now
("i" "Inbox"
entry (file (lambda () (org-gtd--path org-gtd-inbox-file-basename)))
"* %?\n%U\n\n  %i"
:kill-buffer t)
works.
Will check, if any others things do not work due to these changes and come back.

Regards
Poul

**Comment by Trevoke** [comment]
Oh, interesting, thanks. I'll take a look at the release notes and check in as well.

**Comment by Trevoke** [comment]
Is this still happening for you? I am up to org 9.3, I haven't changed my capture patterns, and I'm not running into this issue. Maybe the macro code that I put in the readme was missing the backtick, or something like that?

**Comment by zzamboni** [comment]
@Trevoke FWIW, I was having the same error, and fixed it by replacing the comma with a `lambda` which wraps the call to `org-gtd--path`, as suggested by @poulpoulsen. I am running Emacs 26.3 on macOS, with Org 9.3.6.

**Comment by Trevoke** [comment]
That makes sense -- I'll update the readme. :) thanks.

**Comment by Trevoke** [comment]
Fixed in 7949d08.
