### ISSUE TITLE
Any plan for 2021

### ISSUE THREAD

**Issue by bepolymathe** [Trevoke/org-gtd.el#46]
Hi, 

I find this package very useful but is there a plan for a development in 2021 ?
Just curiosity.
;-)

**Comment by Trevoke** [comment]
Hi @bepolymathe !

I think the best answer is "sort of" ? I've been away from this project for a while, but getting some new interest in working with it and polishing it.
I have a project where some of the work to do is lined up: https://github.com/Trevoke/org-gtd.el/projects/1

And there is a conversation about the workflow here: https://github.com/Trevoke/org-gtd.el/discussions/33

I also need to do some infrastructure work - some of the build fails and I'm not sure why.

Would you have an interest in contributing?

**Comment by bepolymathe** [comment]
Hi @Trevoke 
Thank you for your answer. 
I will try to contribute to the workflow discussion ;-)
