### ISSUE TITLE
Unable to process inbox

### ISSUE THREAD

**Issue by rickyson96** [Trevoke/org-gtd.el#47]
Hi!
I've just stumbled on GTD and trying to use this package while gathering my knowledge through the book.

One thing I stumbled upon when trying out this package is that when I do `org-gtd-clarify-finalize`, I got the error `State ‘NEXT’ not valid in this file`.
I think it is because I don't have `NEXT` in my `org-todo-keywords`.

I can add `NEXT` to my `org-todo-keywords`, but I think we can prevent this from happening by adding `#+TODO:` on the `inbox.org` file.

**Comment by Trevoke** [comment]
Hi @rickyson96 ! 

`org-gtd` should automatically create an inbox for you. Here is what the top of the file looks like:

```org
#+STARTUP: overview hidestars logrefile indent logdone
#+TODO: NEXT TODO WAIT | DONE CANCELED TRASH
#+begin_comment
This is the inbox. Everything goes in here when you capture it.
#+end_comment
```

so if you made an inbox file yourself, yes, you should add NEXT to your TODO keywords :)

**Comment by Trevoke** [comment]
I'm going to close this issue now but please reopen it if org-gtd didn't create the correct inbox file for you.
