### ISSUE TITLE
Can't get process to work

### ISSUE THREAD

**Issue by edhilgendorf** [Trevoke/org-gtd.el#5]
HI, while trying to use process I don't get any feedback and nothing happens to the item (does not get a TODO added, etc). 
I'm not sure where to start, after selecting an option it simply puts me into the inbox on the first item. I love the idea and work here, thank for any input or suggestions!!

Fwiw I have tried this with Spacemacs and Doom emacs.

**Comment by Trevoke** [comment]
Hi! Thanks for trying this out.

I just went over the readme and, you're right, there is *no information whatsoever* there. I need to update the documentation. I'm sorry about this. Let me explain.

When you process the inbox, you go through each entry one at a time.

First, the buffer is hidden, only the first entry is displayed, and you can choose a GTD option. Once you have chosen an option, you are able to edit the entry. You can reword it, add details, whatever you may need. When you are done, hit `C-c C-c`. This will trigger `org-gtd` to do what it needs to do (add the TODO keyword, etc.), and you will then move on to the next entry in your inbox, and repeat the process.

I hope this helps, please let me know what else is unclear!

**Comment by edhilgendorf** [comment]
<img width="265" alt="image" src="https://user-images.githubusercontent.com/7498517/81132187-637c0480-8f02-11ea-9fbd-0b1049308f13.png">
Intersting -- So if I try to capture, then process, and hit "t" for "throw out" I get what is pictured here. C-c C-c does the default function of adding a TAG to an item.

**Comment by Trevoke** [comment]
Oh, *this* is unexpected. Okay. And this is why I I need to figure out how to write tests for this.. :)

Alright, so what must have happened is I've never hit `C-c C-c` on the headline entry. If you move to the timestamp, then hitting `C-c C-c` should work. 

... And I'll have to choose a different key chord for this, I suppose :)

**Comment by Trevoke** [comment]
@edhilgendorf I changed the key binding to `C-c c` - try now.

And yes, org-gtd will add those tags and such, but it won't do them when you see it -- what it does is prep the items *after* you have finished editing them.
