### ISSUE TITLE
Skipping entries when processing inbox

### ISSUE THREAD

**Issue by mobatmedia** [Trevoke/org-gtd.el#50]
How do I skip an element when processing the inbox?

**Comment by cssm** [comment]
I'd like this added to the package as well. My workaround has been to go to inbox.org and using Alt+Up/Down put the items I don't want processed right away at the bottom and the ones I do at the top.

**Comment by cssm** [comment]
You can incubate an item for later in the day or the next day which serves the purpose of skipping an item.

**Comment by mobatmedia** [comment]
Thank you. How do you move items from incubate to inbox

**Comment by Trevoke** [comment]
Hey there!

If you follow GTD, you should process everything that goes into the inbox
according to the decision tree. By far the simplest thing to do, though, is
incubate it. You wouldn't move it from incubate to inbox, because it would
show up in the agenda at the time you scheduled when you incubated it. and
you can always re-schedule it for later from the agenda page if you want it
to disappear for a little while.

**Comment by Trevoke** [comment]
@mobatmedia Please let me know if this solved your issue; I will close this issue in one week if I don't hear back from you.

I am open to "this solved my issue but this isn't how I want to think about it, here is what I would prefer" as well :)

**Comment by mobatmedia** [comment]
Thank you. That sounds good. The one thing left out is to convert the incubated project into a sequence of TODOs headed by a NEXT like any other project. How would I do that?

**Comment by Trevoke** [comment]
There are two way to do that. One would be to capture the project to the inbox, and next time you process the inbox, go through the standard project flow for that item. Nothing stops you from creating the subheadings when you "recapture" it.

I haven't tested another way but it should work in theory. The code for creating a project is:

```elisp
(defun org-gtd--project ()
  "Process GTD inbox item by transforming it into a project.
Allow the user apply user-defined tags from
`org-tag-persistent-alist', `org-tag-alist' or file-local tags in
the inbox.  Refile to `org-gtd-actionable-file-basename'."
  (org-gtd--clarify-item)
  (org-gtd--decorate-item)
  (org-gtd--nextify)
  (org-refile nil nil (org-gtd--refile-target org-gtd-projects))
  (with-current-buffer (org-gtd--actionable-file)
    (org-update-statistics-cookies t)))
```

So you could, I think, create the project headline and the task sub-headlines in the incubate.org, then bring the point to the project heading, call `(org-gtd--nextify)` and then `(org-refile nil nil (org-gtd--refile-target org-gtd-projects))`.

It occurs to me now that I've never done it this way, most of the things I had to incubate were one-offs,this flow should be more straightforward, I'll open a feature request for this.

**Comment by Trevoke** [comment]
I've captured the request to convert an incubated item into a proper project and that'll be in 2.0 -- closing this issue for now, as I believe everything in here has been handled. Please reopen if I missed something (and let me know what I missed).
