### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by mobatmedia** [Trevoke/org-gtd.el#52]
The documentation of the ways of working with org-gtd is missing, so I can only get help from these issues.

**Comment by Trevoke** [comment]
Eep! You're right, that's terrible. I'm about to have a bunch of free time, I will this in the next two weeks (seriously - leaving my job, so I'm gonna have zero excuses)

**Comment by mobatmedia** [comment]
That's so hard core of you. Thanks!

**Comment by Trevoke** [comment]
Well I was *way* more burned out than I thought and I didn't get to this in over a month.

The feature that triggers the change from `TODO -> NEXT` like this is from `org-edna` so you should be able to do `M-x org-edna-load RET`. You may need to manually close and reopen the org-gtd buffers before `org-edna` will work on those buffers again.

I'll prepare something more comprehensive about how this package thinks and how to use it this week.

**Comment by Trevoke** [comment]
Okay, I have finally edited and hopefully cleared up the README some.
I think one of the reasons TODO -> NEXT may have been broken was because org-edna got updated and I didn't adjust the README config to use `(org-edna-mode 1)`. Please let me know if this is better!

**Comment by mobatmedia** [comment]
Thank you. How do I upgrade org-gtd to get the fix in my current setup?

**Comment by Trevoke** [comment]
Hopefully, going through the "Configure" section of the readme should get you setup properly.

I think it's likely you will need to close `actionable.org` manually to get the system working again. Let me know if that is not enough.

**Comment by mobatmedia** [comment]
Thank you.

The configure section asks me to use "use-package" so I installed this one:
    https://github.com/jwiegley/use-package
(Is this package a dependency for org-gtd?) However, use-package errors out saying it "failed to parse package org-gtd". Can you help me figure out how to fix this?

**Comment by mobatmedia** [comment]
I dropped the use of ":pin melpa-stable" in the use-package, not it seems I am in.

**Comment by mobatmedia** [comment]
At this point, every time I process a project from my inbox, it ends up in incubate.org. This has actually been happening for a while.

**Comment by mobatmedia** [comment]
I have verified that the NEXT to DONE triggers the TODO to NEXT. I use customizations in Emacs, so I customized org-edna-use-inheritance to t and org-edna-mode to t, and I saved the change.

**Comment by Trevoke** [comment]
If your projects end up in incubate.org, you might need to clear the refile cache with `(org-refile-cache-clear)` ? What is happening to you is not something I've come across before.

As for `use-package`, I will need to clarify the readme, you do not *need* to use it, but you can choose to, it is a tool to help organize your emacs configuration.

And thank you for verifying that org-edna is working properly!

**Comment by mobatmedia** [comment]
Thank you.

Unfortunately  `(org-refile-cache-clear)` does not resolve the problem.

In `org-gtd--project`, the refiling target `(org-gtd--refile-target org-gtd-projects)` seems to find is in incubate.org at a line with the word "Project". Does that tell you how I can fix this?

**Comment by mobatmedia** [comment]
The `org-gtd--refile-target` function is strange to me. Why does it bind `org-refile-targets` to the value of `(org-gtd--refile-targets)` and then ignore that variable and instead use `(org-refile-get-targets)`? Does that fist line in the `let*` cause a side effect?

`(defun org-gtd--refile-target (heading-regexp)
  "Filters refile targets generated from `org-gtd--refile-targets' using HEADING-REGEXP."
  (let* ((org-refile-targets (org-gtd--refile-targets))
         (results (cl-find-if
                   (lambda (rfloc)
                     (string-match heading-regexp
                                   (car rfloc)))
                   (org-refile-get-targets))))
    results))`

**Comment by Trevoke** [comment]
`org-refile-targets` is a hard-coded variable that is used by `org-mode` when it finds the refile targets, so if I want to create a custom list of refile options, I need to change that variable.

I think in a past refactor I might have lost the line of code where I reset `org-refile-targets` to its prior value.

**Comment by Trevoke** [comment]
Re: refiling finding a target in incubate.org at a line called `Project`, yep, that makes sense, I think I'll need to make some adjustments to how refiling is implemented. The trick is in figuring out a good way to do this that doesn't get in the way of what the user does, because refile targets seem to be limited to ... having a specific tag, or todo keyword, or being at a given level, or having some specific text.

So the simplest thing that would be pretty unambiguous would be a custom tag, I'll have to try this.
