### ISSUE TITLE
Github actions builds are failing. Not sure why. Help!

### ISSUE THREAD

**Issue by Trevoke** [Trevoke/org-gtd.el#66]
See https://github.com/Trevoke/org-gtd.el/commit/13f04f46ed027cd119f21377b050288a96b344cf for example (check out the red X next to the SHA)

**Comment by akirak** [comment]
I've commented on this issue in https://github.com/purcell/setup-emacs/issues/23#issuecomment-945058978. I have never used eldev, but I would suggest you to follow configuration examples using it on CI.

**Comment by Trevoke** [comment]
Fair point. Reaching out to eldev to check, thanks.
