### ISSUE TITLE
Update screenshot in readme of processing menu

### ISSUE THREAD

**Issue by Nimor111** [Trevoke/org-gtd.el#68]
Hello,

First of all, this package looks great, i'm definitely going to give it a spin.

The screenshot of the processing menu in the `README` (e.g. when processing an inbox item what to do with it) seems outdated. I'm using `org-gtd` from the latest master branch and it looks like this:

![org gtd menu](https://i.imgur.com/NxbYcSV.png)

Which isn't the same as shown in the readme: 

![org gtd readme](https://raw.githubusercontent.com/Trevoke/org-gtd.el/master/doc/ogpi-1.png)

Perhaps an update to the `README` is needed? Or am I missing something?

Thank you in advance.

**Comment by Trevoke** [comment]
@Nimor111 Hi! Sorry about the radio silence. I've just released a RC for 2.0, I'd love a pull request with an updated screenshot if you're up for it :)
