### ISSUE TITLE
[Bug]: invalid-function with-org-gtd-refile

### ISSUE THREAD

**Issue by dylantjb** [Trevoke/org-gtd.el#73]
Using the recommended settings under the 2.0.0 branch, I attempted processing an item using any of the GTD actions. For example, when it refiled the item as a single action, it threw me this error after applying tags.

```emacs
Debugger entered--Lisp error: (invalid-function with-org-gtd-refile)
  with-org-gtd-refile("actions" nil "Refile to \"inbox.org\" in file /home/dylan/documents/gtd/inbox.org: done")
  org-gtd-refile--do("actions")
  org-gtd--single-action()
  funcall-interactively(org-gtd--single-action)
  command-execute(org-gtd--single-action)
```

It then refiled itself to inbox with the decorations applied and went to the next item. I have tested this on emacs 27.2.1 and 28.0.90. 

Do you have any ideas for solving this? Thanks!

**Comment by Trevoke** [comment]
Hi @dylantjb , 2.0.0 is almost ready for consumption, though *this* shouldn't have happened and doesn't happen when I run my tests. `with-org-gtd-refile` is a macro available in the `org-gtd-refile.el` file.

Upon receiving this message I've added an autoload cookie to the macro -- for now you can try to evaluate the contents of that file manually, which should load the macro in memory and get rid of that problem for you.

Just in case there's something fundamentally wrong with how I'm setting up the package, how did you install / load the 2.0.0 branch?

**Comment by dylantjb** [comment]
Hello @Trevoke, pulling in the changes and evaluating worked perfectly! Is there a more convenient way of doing this for the time being?

Thanks!

**Comment by Trevoke** [comment]
Oh good!

You should, I think, be able to use https://github.com/raxod502/straight.el to have your config pull/install from the 2.0.0 branch, and $deity willing that should Just Work :tm: .

The 2.0.0 branch is technically in the alpha stage, I am working on fixing up the documentation now and so it should be merged into master, available to MELPA in the next week or so - and hopefully I'll be able to mark it as stable and tag it as 2.0.0 soon thereafter.

**Comment by dylantjb** [comment]
I was referring to going into `org-gtd-refile.el`, finding `with-org-gtd-refile` and evaluating each time I start up emacs. I use a custom recipe with straight.el to clone the branch.

That's good news! The changes look really good which was why I hopped on so early. Looking forward to the stable version!

**Comment by Trevoke** [comment]
@dylantjb Hopefully with the autoload cookie you won't have to do this every time, but I am re-checking documentation to see if there's anything special I need to do to build the package correctly with the autoload cookies.

And thanks for looking ahead :D

**Comment by dylantjb** [comment]
The functions/macros with autoload cookies are generated in org-gtd-autoloads.el when org-gtd is byte compiled, however it did not load them at startup. With 0ee46bccd62a59f8d94ab1ba617c3d75992076b7 it now works. Thanks for everything!
