### ISSUE TITLE
Invalid function with-org-gtd-context

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#75]
Today I upgraded to this commit (abf43ae97e5256a140efa3125355f0b4a1ecbc36)  and every time I execute `org-gtd-engage` I get this message

```
Debugger entered--Lisp error: (invalid-function with-org-gtd-context)
  with-org-gtd-context(nil)
  org-gtd-engage()
  funcall-interactively(org-gtd-engage)
  call-interactively(org-gtd-engage nil nil)
  command-execute(org-gtd-engage)
```

~~Also, processing the inbox seems broken because it does not present the narrowed tree in the inbox file nor the menus to classify the tasks.~~
Skip this part, sorry. I made a silly mistake with my inbox.org. However, the `org-gtd-engage` error persist.

**Comment by Trevoke** [comment]
Hi Maikol,

How did you upgrade? I've had issues with straight.el in my tests.

--

Aldric.

**Comment by Trevoke** [comment]
For now you should be able to manually eval the buffer org-gtd.el and that
should fix your problem -- but obviously that is not something you should
need to do. I have something in mind to change that might help.

--

Aldric.

**Comment by maikol-solis** [comment]
> How did you upgrade? I've had issues with straight.el in my tests.

I upgraded using `(package! org-gtd)` in doom-emacs. I changed the configuration according to the docs.

**Comment by Trevoke** [comment]
Okay - You can upgrade to the most recent on master. You will want to add `(require 'org-gtd)` somewhere in your configuration -- org-gtd is definitely not in a code organization position where it's manageable to do pure autoloads, so it's easier to load all the code at once. Let's call it a work in progress.. 

Let me know if this works for you!

**Comment by Trevoke** [comment]
Another doom user got it to work: https://github.com/Trevoke/org-gtd.el/issues/72#issuecomment-1002364311

Let me know if this helps!

**Comment by maikol-solis** [comment]
Hi! 
Thanks for your help! I think is working again.

My config is this,

```
;;; Org-gtd
(use-package! org-gtd
  :after org
  :config
  (org-edna-mode)
  (setq org-gtd-directory "~/documents/org/gtd")
  (setq org-gtd-default-file-name "actionable")
  (setq org-edna-use-inheritance t)
  (map!
   :leader
   (:prefix-map ("d" . "org-gtd")
    :desc "Capture"        "c"  #'org-gtd-capture
    :desc "Engage"         "e"  #'org-gtd-engage
    :desc "Process inbox"  "p"  #'org-gtd-process-inbox
    :desc "Show all next"  "n"  #'org-gtd-show-all-next
    :desc "Stuck projects" "s"  #'org-gtd-show-stuck-projects
    :map org-gtd-process-map
    :desc "Choose"         "C-c" #'org-gtd-choose)))

```

However, the only glitch found is when I execute `org-gtd-engage` it appears this message in the minibuffer
```
Warning: Condition specified without targets 
```

**Comment by maikol-solis** [comment]
Just for the record, 

I changed the config to this one for better support with `org-gtd-choose`

```
;;; Org-gtd
(use-package! org-gtd
  :after org
  :config
  (org-edna-mode)
  (setq org-gtd-directory "~/documents/org/gtd")
  (setq org-gtd-default-file-name "actionable")
  (setq org-edna-use-inheritance t)
  (map!
   :leader
   (:prefix-map ("d" . "org-gtd")
    :desc "Capture"        "c"  #'org-gtd-capture
    :desc "Engage"         "e"  #'org-gtd-engage
    :desc "Process inbox"  "p"  #'org-gtd-process-inbox
    :desc "Show all next"  "n"  #'org-gtd-show-all-next
    :desc "Stuck projects" "s"  #'org-gtd-show-stuck-projects))

  (map!
   :map org-gtd-process-map
   :desc "Choose"         "C-c C-c" #'org-gtd-choose))
```

**Comment by Trevoke** [comment]
Thank you for sharing! I think I might need to add something like this to the documentation. I'll look into the warning message as well. Closing this for now, please open new issues for anything else that comes up!
