### ISSUE TITLE
Org-gtd should warn the user the right format for a project

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#82]
Suppose you have a single heading

```
* My single item project
```

If the user is in the clarify part (`org-gtd-choose`) and select `Project`, `org-gtd` triggers this error 

```
Debugger entered--Lisp error: (wrong-number-of-arguments (first-entry . rest-entries) 0)
  signal(wrong-number-of-arguments ((first-entry . rest-entries) 0))
  org-gtd-projects--nextify()
  org-gtd--project()
  funcall-interactively(org-gtd--project)
  call-interactively(org-gtd--project nil nil)
  command-execute(org-gtd--project)
```

The problem is that expect format is

```
* My correct formated project
* * First task
```

`org-gtd` should warn the user when the format is incorrect. 

Best.

**Comment by Trevoke** [comment]
I added a message that will pop up in the minibuffer or a message window when the user enters a single heading and selects "project".

**Comment by maikol-solis** [comment]
It works flawlessly. Thanks!
