### ISSUE TITLE
org-gtd-engage presents the wrong day in agenda

### ISSUE THREAD

**Issue by maikol-solis** [Trevoke/org-gtd.el#84]
Hi again!

I discovered a little glitch with `org-gtd-engage`. 

Today is Sunday, January 9th, and when I want to see the agenda with my NEXT items I have something like this

![image](https://user-images.githubusercontent.com/4078489/148683285-0d110393-8c2f-4ad7-a9ad-d92e27104368.png)

If you notice, the agenda view is set to Thursday, January 6th (3 days in the past). 

I assume that the problem comes from the `org-agenda-span` in this defcustom https://github.com/Trevoke/org-gtd.el/blob/master/org-gtd-customize.el#L91. 

For me, it seems right, but I don't know what is causing this behavior. 

Thanks for your help.

**Comment by maikol-solis** [comment]
Problem solved! 

Doom-emacs forces to start the agenda 3 days in the past (https://github.com/hlissner/doom-emacs/commit/1bbf5b7d190f1989d0f6f912c3c8e02ae7ee8ee0)

Setting 
```
(setq org-agenda-start-day nil)
```
in your `org-gtd` block solves the issue. 

Best

**Comment by Trevoke** [comment]
Good call! I fixed it for future users by enforcing that value in the custom agenda command for org-gtd, like so:

```emacs-lisp
(defcustom org-gtd-agenda-custom-commands
  '(("g" "Scheduled today and all NEXT items"
     (
      (agenda "" ((org-agenda-span 1)
                  (org-agenda-start-day nil)))
      (todo "NEXT" ((org-agenda-overriding-header "All NEXT items")))
      (todo "WAIT" ((org-agenda-todo-ignore-with-date t)
                    (org-agenda-overriding-header "Blocked items"))))))
```

For you, your fix will work for this, and if/when you start using the agenda differently, this will be a way for you to make adjustments per-command.

When I make further agenda views, I'll be sure to specify this kind of setting explicitly :D

**Comment by maikol-solis** [comment]
Thanks!
