### ISSUE TITLE
[Help] how to use org-gtd for multiple projects? 

### ISSUE THREAD

**Issue by poulpoulsen** [Trevoke/org-gtd.el#88]
hello,
i try to understand, how i could use gtd for my multiple projects, but it doesnt work.
scenario:
i use a flat directory with my org files. the first top item has the properties, you described.
* Held
:PROPERTIES:
:TRIGGER: next-sibling todo!(NEXT)
:ORG_GTD: Projects
:ID:       fdacc6c3-f48b-4f99-98f5-42e53108589f
:END:

but this is not shown or selectable during the inbox processing with C-c c and then "project"
the display shows a message how to create a project file.

what else do i have to configure, so that org-gtd recognize my files?

Thanks
Poul

**Comment by Trevoke** [comment]
Hmm, that's weird. Those are the correct heading properties. 

This file is in the directory `org-gtd-directory`, I gather from your message?
And I imagine the file exists and is more than just a buffer?


And to be clear, what you're trying to refile as a project is a heading with subheadings, right?

```
* Foo
** Bar
** Baz
```

Something like that?

**Comment by Trevoke** [comment]
Can you show me what the refined inbox item that you want to try to make
into a project looks like?

**Comment by Trevoke** [comment]
Hi @poulpoulsen , is this issue solved?

**Comment by poulpoulsen** [comment]
Hello and a happy New year!
I can not say if it is solved, because i switched away from org-gtd. You 
can close the ticket.
Sorry for the noise.
Regards

----------------------------------------

Von: Trevoke ***@***.***>
An: Trevoke/org-gtd.el ***@***.***>
Kopie: poulpoulsen ***@***.***>; Mention 
***@***.***>
Datum: 08.01.2023 21:41:13
Betreff: Re: [Trevoke/org-gtd.el] [Help] how to use org-gtd for multiple 
projects? (Issue #88)

**Comment by Trevoke** [comment]
No worries, and happy new year! I hope you found a solution that works for you :)
