### ISSUE TITLE
Cannot archive project when its items have different states in `org-done-keywords`

### ISSUE THREAD

**Issue by bohonghuang** [Trevoke/org-gtd.el#91]
The following project items, for example, will keep the project from being archived by `org-gtd-archive-completed-items`: 

![图片](https://user-images.githubusercontent.com/11132087/165080746-3ed44a13-a780-407a-bb73-6a3ea54d470b.png)

**Comment by Trevoke** [comment]
Hmm, good point. I've never had a project where canceling a task meant the
project continued but there's no reason why that couldn't be the case.
