### ISSUE TITLE
Allow refiling tasks into project when processing inbox

### ISSUE THREAD

**Issue by herder** [Trevoke/org-gtd.el#98]
From [this](https://discord.com/channels/723999634594201600/911343828433244211/1029729712974594098) Discord discussion:

When processing the inbox, the "Project" goal currently requires that you have selected a header with a subheader, otherwise nothing happens.

More intuitive (imho) would be to be able to put (i.e. refile) the task into a current project, or if needed create a new project heading and put the task under it.

If a project already has items it might be nice to be able to select what order to put the new task in, but if that is too difficult to implement it might be good to add it at the top, to not risk forgetting it. That way it will surface directly after the top item in the project is set to done, so you get a prompt to change the ordering if needed.

**Comment by Trevoke** [comment]
I've just merged in code that allows one to move a task to an existing project! Try it when MELPA updates and let me know how it goes :D
